---
- hosts: all
  become: true
  tasks:
  - name: stop all docker containers
    command: docker stop $(docker ps -aq)
    ignore_errors: yes

  - name: remove all doker containers
    command: docker rm $(docker ps -aq)
    ignore_errors: yes

  - name: remove all docker images
    command: docker rmi $(docker images -q)
    ignore_errors: yes

  - name: building docker image
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: create container using simple-devops-image
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image
